iss_cmp, iss_sim, scripts/instr_trace_compare.py
Save the log to a separate report file
Add rerun command in the regression report
Add more options to iss_sim and iss_cmp script
=> Refine the regression and checking script

README.md, src/riscv_instr_pkg.sv, src/riscv_page_table_list.sv
I believe my company rep signed the Google CLA this morning.
=> Fix typos/grammar in README & code comments

run, src/riscv_illegal_instr.sv, src/riscv_instr_pkg.sv
- Fix illegal instruction test issue
- Fix Xcelium compile failure #37
=> Fix illegal instruction test issue

src/riscv_instr_gen_config.sv, src/riscv_rand_instr.sv, test/riscv_instr_test_lib.sv
- Default enable CSR instruction
- Add illegal CSR instruction support
=> CSR instruction update

README.md, questa_sim.tcl, run, src/dv_defines.svh, src/riscv_asm_program_gen.sv, src/riscv_instr_sequence.sv
We noticed that the seed was not working for Xcelium so we fixed that
We got new compile and simulation warnings when we ran on Questa so we fixed those
We are unable to test these changes on VCS but we made sure that Xcelium still works
Please see individual commit messages for details of the changes made
=> Add support for Mentor Questa simulator, fix seed and other warnings

README.md, src/riscv_instr_base.sv, src/riscv_page_table_list.sv
This is a redo of #8 which was rejected because of an issue with the CLA. I believe this should not be an issue anymore: when I visit `https://cla.developers.google.com/clas` it shows that I am covered under "Google Corporate CLA" agreement under name "Aril Computer Corp" signed Feb 26.
=> Fix typos in README & comments

.gitignore, run, src/riscv_illegal_instr.sv
Hi, I make PR to fix minor warning Questa simulator.
=> Fix minor warning Questa simulator

iss_cmp, iss_sim, run.py, scripts/instr_trace_compare.py, scripts/ovpsim_log_to_trace_csv.py, scripts/spike_log_to_trace_csv.py, scripts/testlist_parser.py, src/riscv_asm_program_gen.sv, src/riscv_instr_gen_config.sv, src/riscv_rand_instr.sv, yaml/simulator.yaml, yaml/testlist.yaml
Refactor the comparison scripts to be easily integrated to the new run flow.
=> Refactor the simulation flow

scripts/instr_trace_compare.py, scripts/ovpsim_log_to_trace_csv.py, scripts/spike_log_to_trace_csv.py, scripts/testlist_parser.py
=> Update log process script

run.py, scripts/lib.py
=> Add timeout mechanism to the flow 

README.md
=> Update README file for the new flow

README.md
=> changed formatting of generator option table

README.md
=> Update the README.md to match command reference from --help

run.py
Hi, I make a PR to minor modify the run.py script. Could you review it when you have the chance? Thank you
=> Add main entry point for run.py

run.py, scripts/lib.py, scripts/ovpsim_log_to_trace_csv.py, scripts/spike_log_to_trace_csv.py
Hi, I make PR to enhance verbose information by logging instead of using `print`. Could you review it when you have the chance?
=> Enhance verbose information by logging instead of using print

run.py
I make PR to add shorten option.
=> Add shorten option

README.md, scripts/instr_trace_compare.py, src/riscv_asm_program_gen.sv, src/riscv_instr_gen_config.sv, src/riscv_instr_sequence.sv, test/riscv_instr_base_test.sv
- Modify instruction generator to generate a very basic debug rom, contains random instruction stream
- Modify trace comparison script to change outdated primitive types
=> Add basic debug test functionality

run.py, src/riscv_directed_instr_lib.sv, src/riscv_instr_gen_config.sv, yaml/testlist.yaml
- non-compressed instruction test
- unaligned load/store test
update #77
=> Add new tests

src/riscv_instr_gen_config.sv
=> Fix ius compilation failure

src/riscv_instr_stream.sv
=> fix ius compile/simulation warnings

src/riscv_asm_program_gen.sv, src/riscv_instr_sequence.sv
=> Optimize irun randomization performance

src/riscv_instr_base.sv, src/riscv_instr_pkg.sv, src/riscv_instr_stream.sv
=> Optimize for constraint solving performance

files.f, run.py, scripts/lib.py
=> Allow running riscv-dv from other directories

run.py, src/riscv_asm_program_gen.sv, test/riscv_instr_base_test.sv
=> Refine the bare program mode

scripts/link.ld, src/riscv_asm_program_gen.sv, src/riscv_data_page_gen.sv, src/riscv_page_table.sv, src/riscv_page_table_list.sv, yaml/testlist.yaml
=> Re-organize text and data section

1
=> Move dv_defines.svh outside the package

run.py, scripts/lib.py, src/riscv_asm_program_gen.sv, src/riscv_instr_base.sv
=> Fix RV64A typo

cov.py, run.py, scripts/riscv_trace_csv.py, scripts/spike_log_to_trace_csv.py, src/riscv_asm_program_gen.sv, src/riscv_illegal_instr.sv, src/riscv_instr_base.sv, src/riscv_instr_cov_item.sv, src/riscv_instr_cover_group.sv, src/riscv_instr_gen_config.sv, src/riscv_instr_pkg.sv, src/riscv_rand_instr.sv, test/riscv_instr_base_test.sv, test/riscv_instr_cov_debug_test.sv, test/riscv_instr_cov_test.sv, test/riscv_instr_test_pkg.sv, yaml/cov_testlist.yaml, yaml/simulator.yaml
Collect functional coverage from spike simulation log
This is still working in progress, expect some bug fixes soon.
update #131
=> Initial prototype of functional coverage (RV32I)

src/riscv_instr_cov_item.sv, src/riscv_instr_cover_group.sv, src/riscv_instr_pkg.sv
=> Add basic functional coverage for RV64IMC

src/riscv_instr_cov_item.sv, src/riscv_instr_cover_group.sv, src/riscv_instr_pkg.sv
=> Add functional coverage for various hazard conditions

src/riscv_illegal_instr.sv, src/riscv_instr_cov_item.sv, src/riscv_instr_cover_group.sv, test/riscv_instr_cov_test.sv
=> Add functional coverage for HINT instructions

scripts/spike_log_to_trace_csv.py
=> Fix spike logging issue

setting/riscv_core_setting.sv, src/riscv_instr_cover_group.sv
=> Add basic privileged CSR cover group

src/riscv_asm_program_gen.sv, src/riscv_instr_gen_config.sv, src/riscv_instr_stream.sv, src/riscv_load_store_instr_lib.sv, src/riscv_rand_instr.sv, yaml/testlist.yaml
=> Add support for disable_compressed_instr

README.md, run.py
=> Fix non-compressed instruction test

run.py
=> Fix disable_compressed_instr option

yaml/simulator.yaml
=> Update questa covearge options

cov.py
Hi,
I make a PR that it can run coverage with different simulator.
vcs is a default simulator.
=> cov.py: Allow coverage to run with different simulator

yaml/simulator.yaml
Hi,
The output UCDB file is generated outside output directory. So, I make PR to generate the ucdb file inside output directory.
=> Generate the ucdb file inside output directory

scripts/gen_csr_test.py
=> Fix CSR test setup

.gitignore, cov.py, questa_sim.tcl, scripts/ovpsim_log_to_trace_csv.py, src/riscv_instr_cover_group.sv, test/riscv_instr_cov_test.sv
=> Fixed default values, and trailing blank lines

.gitignore, cov.py, run.py, src/riscv_instr_base.sv, src/riscv_instr_gen_config.sv, target/rv32i/riscv_core_setting.sv, target/rv32i/testlist.yaml, target/rv32imc/riscv_core_setting.sv, target/rv32imc/testlist.yaml, yaml/testlist.yaml
=> Testlist clean up, add RV32I target

run.py, scripts/ovpsim_log_to_trace_csv.py, scripts/riscv_trace_csv.py, target/rv32i/riscvOVPsim.ic, target/rv32imc/riscvOVPsim.ic, target/rv64imc/riscvOVPsim.ic, yaml/iss.yaml
Updated OVPsim log processing for coverage
Added OVPsim config files as targets
=> Updating OVPsim device configuration and coverage processing

src/riscv_directed_instr_lib.sv
=> Fix dsim compilation issue

run.py, setting/riscvOVPsim.ic, target/rv32imc/riscvOVPsim.ic, target/rv64imc/riscvOVPsim.ic, yaml/iss.yaml
=> Fix ovpsim sim problem

run.py, target/rv32imc/testlist.yaml, target/rv64imc/riscvOVPsim.ic, target/rv64imc/testlist.yaml, yaml/testlist.yaml
=> Fix compressed instruction test setup

scripts/lib.py, src/riscv_instr_base.sv, src/riscv_instr_cov_item.sv
=> Fix duplicate

src/riscv_illegal_instr.sv
Added a new type of illegal instruction: `kIllegalSystemInstr`.
This is meant to stress invalid `SYSTEM`-type instructions that present both a valid `opcode` and `funct3` field to the processor's decoding logic.
=> Update illegal system instr generation

src/riscv_asm_program_gen.sv
=> Fix misa setup issue

run.py, scripts/ovpsim_log_to_trace_csv.py, yaml/iss.yaml
changes to fix some trace handling problems
changed cfg_path to variant for selecting correct configuration file to riscvOVPsim
=> fixed trace handling issues

cov.py, scripts/ovpsim_log_to_trace_csv.py, scripts/riscv_trace_csv.py, src/riscv_asm_program_gen.sv
tidied up ine widths, comments and function comments
=> adding riscvOVPsim vector instruction trace to csv processing - start (3rd Attempt)

scripts/ovpsim_log_to_trace_csv.py
made unknown instuctions be ignored
=> Unknown instruction fix

.gitignore, cov.py, run.py
=> Fix cov.py, set UVM_VERBOSITY to UVM_HIGH for verbose mode

cov.py, run.py, scripts/lib.py, scripts/riscv_trace_csv.py, test/riscv_instr_cov_test.sv
=> Add a generic approach to check command return value

scripts/ovpsim_log_to_trace_csv.py, src/riscv_instr_base.sv, test/riscv_instr_cov_test.sv
=> Fix ovpsim log parsing issue

src/riscv_rand_instr.sv
addresses https://github.com/lowRISC/ibex/issues/485
=> enable CSR randomization only for csr instructions

cov.py, run.py, scripts/gen_csr_test.py, scripts/lib.py
I make PR for minor refactor the code for compile, and simulate
=> Run.py: minor refactor the code for compile, and simulate

.gitignore, README.md, cov.py, run.py, scripts/lib.py, yaml/simulator.yaml
Hi,
I create PR to minor fix for cov.py
=> Add support coverage flow for qrun, and minor fix for cov.py

.gitignore, README.md
Hi,
I make PR to fix the link for `yaml/base_testlist.yaml` in README
=> Fix the link for yaml/base_testlist.yaml

README.md, scripts/lib.py
I make PR to support running specific multiple tests
Fixed #345
=> Support running specific multiple tests

src/riscv_amo_instr_lib.sv
=> Fix lr/sc sequence

cov.py, run.py, scripts/lib.py, scripts/ovpsim_log_to_trace_csv.py, scripts/sail_log_to_trace_csv.py, scripts/spike_log_to_trace_csv.py, scripts/whisper_log_trace_csv.py
I make PR to remove some unused variable in script.
=> Remove unused variable

cov.py, src/riscv_instr_cover_group.sv, test/riscv_instr_cov_test.sv
=> Add compliance mode to coverage model

README.md, run.py, scripts/instr_trace_compare.py
=> Support running regression with hand-coded assembly tests

scripts/ovpsim_log_to_trace_csv.py
=> Fix mie compare mismatch

run.py
=> Ignore return code for ovpsim sim

src/isa/riscv_instr.sv
=> Fix qrun issue, take 2

README.md, cov.py, run.py
I make PR to enhance passing argument. I try to run some test cases
Fixed #373
```
python3 run.py --test riscv_arithmetic_basic_test --iterations 10 --simulator qrun
python3 run.py --test riscv_arithmetic_basic_test --simulator qrun
python3 run.py --test riscv_arithmetic_basic_test --verbose --simulator qrun
python3 run.py --test riscv_arithmetic_basic_test --seed 123 --simulator qrun
python3 run.py --test riscv_arithmetic_basic_test --steps iss_sim --simulator qrun
python3 run.py --test riscv_arithmetic_basic_test --steps gen --simulator qrun
python3 run.py --test riscv_arithmetic_basic_test --co --simulator qrun --noclean
```
I only can test `riscv_arithmetic_basic_test` because I got block by this issue #374
=> run.py: Enhance passing argument for gen function

README.md, run.py
Hi, I make PR to support flexible running directed assembly tests
Fixed #385
=> Support flexible running directed assembly tests

run.py, scripts/exp/exp_instr_trace_compare.py, scripts/exp/exp_ovpsim_log_to_trace_csv.py, scripts/exp/exp_riscv_trace_csv.py, scripts/exp/exp_spike_log_to_trace_csv.py, scripts/lib.py
Sample format:
pc,instr,gpr,csr,binary,mode,instr_str,mem_addr
ffffffff80000004,,ra:e2c32000,,e2c320b7,3,"lui     ra, 0xe2c32",
ffffffff80000008,,ra:e2c3212e,,12e08093,3,"addi    ra, ra, 302",
ffffffff80008264,csrw,,sstatus:000c0000;mstatus:001c1800,300f9073,3,"csrw    mstatus,t6",
Can pass rv32imc regression now, need more work to integrate with coverage flow
update #300
=> Add experimental script for the new CSV format

src/isa/riscv_instr.sv
=> Fix simulation warning

src/riscv_instr_stream.sv
=> Try fix qrun constraint solver issue

src/isa/riscv_instr.sv
=> Fix qrun sim warning

src/riscv_asm_program_gen.sv, src/riscv_instr_gen_config.sv, src/riscv_instr_pkg.sv, src/riscv_privil_reg.sv, src/riscv_privileged_common_seq.sv, src/riscv_vector_cfg.sv, target/rv64gcv/testlist.yaml
=> Add vector CSR initialization routine

cov.py
I make PR for generating error when it cannot find `spike_sim` directory
=> Generate error when it cannot find spike_sim directory

test/riscv_instr_cov_test.sv
=> Fix typo in cov_test

src/riscv_instr_pkg.sv
=> Fix coverage flow issue

README.md, cov.py
I send the patch to refactor the code for cov.py
=> Refactor the code for cov.py

.gitignore, MANIFEST.in, README.md, setup.cfg, setup.py
I make PR for python package.
Relate to: #418
=> Python package

README.md, setup.cfg
I make PR to update information about instruction for running scripts
=> Update information about instruction for running scripts

cov.py, run.py
I make PR to handle KeyboardInterrupt
=> Add try-except for handling KeyboardInterrupt

docs/Makefile, docs/make.bat, docs/source/conf.py, docs/source/index.rst
I make PR to add initial Sphinx docs.
Relate to issue #425
=> Add initial Sphinx docs

README.md
I make PR to update the information relating to usage
=> README.md: Update the information relating to usage

.travis.yml, docs/Makefile
I make PR for adding setup Travis CI to track build docs, and install.
=> Add setup Travis CI for tracking build docs, and install

docs/riscv-dv.pdf, docs/source/conf.py, requirements.txt
I make PR to generate pdf file
relate #425
=> Sphinx: Add generating pdf file

run.py
I send PR to resolve issue relating to pass gcc_opts from YAML for GCC compile command
=>  Resolve: missing pass gcc_opts from YAML for GCC compile command 

src/isa/custom/riscv_custom_instr.sv, src/isa/custom/riscv_custom_instr_enum.sv, src/isa/custom/rv32x_instr.sv, src/isa/custom/rv64x_instr.sv, src/riscv_asm_program_gen.sv, src/riscv_defines.svh, src/riscv_instr_pkg.sv, target/rv64gc/riscv_core_setting.sv
=> Add framework for custom extensions

cov.py, run.py, scripts/lib.py
=> Implement storing the commands that would be executed as a script

run.py
I create PR to support C test. It looks the same as running assembly test except the option, file on command. I will enhance after it works. I try to write a simple C file, Unfortunately, it does not work.
Example:
$ run --c_test test.c --debug debug.log -o c_test
Debug command:
```
/opt/riscv/bin/riscv64-unknown-elf-gcc -mcmodel=medany -nostdlib -nostartfiles test.c -I/home/danghai/hhoangda/riscv-dv/user_extension -T/home/danghai/hhoangda/riscv-dv/scripts/link.ld -o c_test/directed_c_tests/test.o -march=rv32imc -mabi=ilp32
/opt/riscv/bin/riscv64-unknown-elf-objcopy -O binary c_test/directed_c_tests/test.o c_test/directed_c_tests/test.bin
/opt/riscv/bin/spike --log-commits --isa=rv32imc -l c_test/directed_c_tests/test.o &> c_test/spike_sim/test.log
```
=> Support running C test

docs/source/getting_started.rst, run.py, yaml/base_testlist.yaml
I make PR to integrate directed C test with yaml flow.
Issue #440
=> Integrate directed C test with yaml flow

src/riscv_amo_instr_lib.sv
=> Fix LR/SC instruction issue for RV32A

src/riscv_instr_gen_config.sv
=> Add a runtime option to fix stack pointer

README.md
=> add path for the prebuilt document

run.py, src/riscv_asm_program_gen.sv, src/riscv_data_page_gen.sv, src/riscv_debug_rom_gen.sv, src/riscv_directed_instr_lib.sv, src/riscv_instr_gen_config.sv, src/riscv_instr_pkg.sv, src/riscv_instr_stream.sv, src/riscv_page_table_list.sv, src/riscv_privileged_common_seq.sv, target/ml/riscvOVPsim.ic, target/multi_harts/riscvOVPsim.ic, target/multi_harts/riscv_core_setting.sv, target/multi_harts/testlist.yaml, target/rv32i/riscvOVPsim.ic, target/rv32i/riscv_core_setting.sv, target/rv32imc/riscv_core_setting.sv, target/rv64gc/riscv_core_setting.sv, target/rv64gcv/riscv_core_setting.sv, target/rv64imc/riscvOVPsim.ic, target/rv64imc/riscv_core_setting.sv
- Refactor the instruction generator to support multi-harts
- Created a multi-harts target
update #462
=> Add multi-thread support

src/riscv_asm_program_gen.sv
=> User long jump to switch between different harts

src/riscv_pmp_cfg.sv
=> fix pmp/shifted_addr compile warning

scripts/gen_csr_test.py
=> add seed capability to CSR test generation

src/riscv_asm_program_gen.sv, src/riscv_data_page_gen.sv, src/riscv_instr_gen_config.sv
=> Use .section for data sections by default

src/riscv_asm_program_gen.sv, src/riscv_directed_instr_lib.sv
=> Avoid jumping to a sub program of other harts

src/riscv_asm_program_gen.sv, src/riscv_instr_gen_config.sv, yaml/simulator.yaml
Reduce the AMO region size (default 1 section with 64B)
Fix data section 
update #496 #462
=> Update AMO region and data sections

src/riscv_directed_instr_lib.sv, src/riscv_load_store_instr_lib.sv
=> Fix hart id assignment for load/store instruction stream

src/riscv_directed_instr_lib.sv, src/riscv_load_store_instr_lib.sv, target/multi_harts/testlist.yaml
=> Add load/store shared memory test

src/riscv_asm_program_gen.sv, src/riscv_data_page_gen.sv
=> Add section for each data region

src/riscv_asm_program_gen.sv
=> Remove alignment constraint

src/riscv_amo_instr_lib.sv, target/multi_harts/testlist.yaml
=> Fix AMO sequence address generation issue

src/riscv_amo_instr_lib.sv
=> Fix ius constraint solver failure

verilog_style/build-verible.sh
Needed to fix https://github.com/google/verible/issues/222
=> Bump verible

run.py, src/isa/riscv_instr.sv, src/riscv_illegal_instr.sv, src/riscv_instr_gen_config.sv
=> Fix illegal func3/func7 instruction generation for B-extension

src/isa/riscv_b_instr.sv, src/isa/riscv_instr.sv, src/riscv_instr_gen_config.sv, src/riscv_instr_pkg.sv, target/rv32imcb/testlist.yaml
Also add a test that enables ZBB only
=> Add options to enable bitmanip by group

src/riscv_pmp_cfg.sv
This constrains randomization of pmp address to all still lie within the address range defined by:
```systemverilog
[<main> : <main> + pmp_max_offset]
```
Additionally an enable flag is added to control whether randomized addresses can overlap.
=> fix pmp randomization to adhere to max offset

MANIFEST.in, README.md, docs/source/getting_started.rst, riviera_sim.tcl, scripts/lib.py, src/riscv_asm_program_gen.sv, src/riscv_instr_pkg.sv, src/riscv_pmp_cfg.sv, yaml/simulator.yaml
Changes in original code are are made to make it compatible with Riviera-PRO.
Some changes have comments to make it clear why they are needed.
I closed previous pull request on this topic to clean the history.
=> Initial Aldec Riviera-Pro simulator support

src/riscv_instr_pkg.sv
Fix for #538
1. add default parameter type for cmdline_enum_processor
2. update change from #535
=> Fix ius compile error

run.py, src/isa/riscv_b_instr.sv, src/isa/riscv_instr.sv, target/rv64imcb/riscvOVPsim.ic, target/rv64imcb/riscv_core_setting.sv, target/rv64imcb/testlist.yaml
Add this target to test b-ext 64b for #520
Update imm value logic in riscv_b_instr to support 64b
=> Add target rv64imcb

test/riscv_instr_test_lib.sv
=> Fix typo in riscv_instr_test_lib

src/riscv_instr_cov_item.sv, src/riscv_instr_cover_group.sv, test/riscv_instr_cov_test.sv
Add coverage support for instructions section 2.1-2.4
For task #520
=> B extension coverage part1

src/isa/riscv_b_instr.sv, src/riscv_instr_cover_group.sv, test/riscv_instr_cov_test.sv
For task #520
1. Add coverage for the rest of sections
2. Minor fix in riscv_b_instr
Signed-off-by: Weicai Yang <weicai@google.com>
=> B extension coverage part2

src/riscv_instr_cov_item.sv
=> Fix branch hit coverage issue

src/riscv_instr_sequence.sv
=> Change generate_instr_stream to a virtual function

src/isa/riscv_vector_instr.sv
=> Fix vector instruction randomization

src/riscv_pmp_cfg.sv
Currently in this PMP handling routine, if an access doesn't match any of the implemented PMP regions, we simply exit the handling routine and continue execution.
However the spec mandates that an access that doesn't match any PMP region only succeeds if it was made from M-mode - as a result, this PR adds functionality to jump to `test_done` if an access that doesn't match any PMP region was made from anything other than M-mode.
=> fix bug in PMP handler routine

run.py
=> Check return code for ovpsim

pygen/experimental/riscv_asm_program_gen.py, pygen/experimental/riscv_instr_base.py
I send PR to minor fix for running riscv_asm_program_gen.py
=> PR to minor fix for running riscv_asm_program_gen.py

yaml/simulator.yaml
=> Add Xcelium support

src/riscv_pmp_cfg.sv
=> Add missing default case to pmp_config

src/isa/riscv_instr.sv
=> Fix VSETVL generation issue

src/riscv_page_table_list.sv
=> Fix kernal setcion  PTE setting issue

src/isa/riscv_vector_instr.sv, src/riscv_load_store_instr_lib.sv, target/rv64gcv/testlist.yaml
This test is conributed by Andes, refactored to follow the latest instruction randomization flow
=> Add vector strided load/store test

pygen/pygen_src/isa/riscv_instr.py, pygen/pygen_src/isa/rv32i_instr.py, pygen/pygen_src/riscv_defines.py, pygen/pygen_src/test/riscv_instr_base_test.py
=> Update pygen source files

src/riscv_vector_cfg.sv, target/ml/riscv_core_setting.sv, target/multi_harts/riscv_core_setting.sv, target/rv32imc/riscv_core_setting.sv, target/rv32imcb/riscv_core_setting.sv, target/rv64gc/riscv_core_setting.sv, target/rv64gcv/riscv_core_setting.sv, target/rv64imc/riscv_core_setting.sv, target/rv64imcb/riscv_core_setting.sv
=> Add MAX LMUL configure

src/isa/riscv_floating_point_instr.sv, src/riscv_instr_cover_group.sv
for #443, including all remaining items
1. 11.7-11.9
2. chapter 12 double precision
3. floating point special values
=> Add floating point coverage part2

src/riscv_asm_program_gen.sv
=> Fix vector extension config register initialization

src/isa/riscv_vector_instr.sv, target/rv64gcv/testlist.yaml
=> Fix vector load/store instruction encoding

src/isa/riscv_floating_point_instr.sv, src/isa/riscv_instr_cov.svh, src/riscv_asm_program_gen.sv, src/riscv_instr_cover_group.sv, src/riscv_instr_pkg.sv, test/riscv_instr_cov_test.sv
Also update coverage and fix some unreachable cover points
relate to task #443
=> Update init value for floating point reg

src/isa/riscv_b_instr.sv
=> Fix B-ext instruction generation issue

pygen/pygen_src/isa/riscv_instr.py, pygen/pygen_src/isa/rv32i_instr.py, pygen/pygen_src/riscv_defines.py, pygen/pygen_src/riscv_instr_gen_config.py, pygen/pygen_src/riscv_instr_pkg.py, pygen/pygen_src/target/rv32i/riscv_core_setting.py, pygen/pygen_src/test/riscv_instr_base_test.py
The conversion is based on <https://github.com/saurabhsingh-pvips/riscv-dv/tree/master/src> riscv-dv version.
=> Update pygen_src files

pygen/pygen_src/isa/riscv_instr.py, pygen/pygen_src/riscv_instr_gen_config.py, requirements.txt
Just imported pyvsc into riscv_instr.py and riscv_instr_gen_config.py.
=> Importing PyVSC module

src/isa/riscv_instr.sv, src/riscv_asm_program_gen.sv, src/riscv_instr_gen_config.sv, target/rv64gcv/testlist.yaml
=> Support a vetor instruction only mode

pygen/pygen_src/riscv_instr_stream.py
The original **riscv_instr_stream.sv** file for reference <https://github.com/saurabhsingh-pvips/riscv-dv/blob/master/src/riscv_instr_stream.sv>
=> [Pygen] Add riscv_instr_stream file

src/isa/riscv_instr.sv
=> Add unsupported load/store instruction filtering

src/riscv_instr_gen_config.sv
=> Add constraint for mtvec alignment in vectored interrupt mode

src/isa/riscv_instr.sv, src/isa/riscv_vector_instr.sv, src/riscv_asm_program_gen.sv, src/riscv_instr_gen_config.sv, src/riscv_instr_stream.sv, src/riscv_load_store_instr_lib.sv, src/riscv_vector_cfg.sv, target/rv64gcv/testlist.yaml
=> Add indexed/strided vector load/store instrution stream

src/riscv_instr_sequence.sv
Hey!
I think we need to convert `*main*` to regular expressions by `uvm_glob_to_re`
=> added uvm_glob_to_re in uvm_re_match

pygen/pygen_src/isa/riscv_instr.py, pygen/pygen_src/isa/rv32i_instr.py, pygen/pygen_src/riscv_asm_program_gen.py, pygen/pygen_src/riscv_defines.py, pygen/pygen_src/riscv_instr_gen_config.py, pygen/pygen_src/riscv_instr_pkg.py, pygen/pygen_src/riscv_instr_sequence.py, pygen/pygen_src/riscv_instr_stream.py, pygen/pygen_src/target/rv32i/riscv_core_setting.py, pygen/pygen_src/test/riscv_instr_base_test.py
Generated assembly file 
- Immediate values are not up to the mark because **extend_imm()** function and constraint of **self.imm** variable are not up yet. [RESOLVED] in  <https://github.com/google/riscv-dv/tree/949f666959bfb8c65bc92db71c731523a8dcf1c0> commit.
In test directory
`python3 riscv_instr_base_test.py`
=> [Pygen] Add Complete flow for RV32I instructions

pygen/pygen_src/riscv_instr_gen_config.py
Command-line support for Pygen.
=> [Pygen] Add Command Line Support

target/rv32i/riscv_core_setting.sv
Fixes compilation error as described in #643
=> add MAX_LMUL to rv32i config

.gitignore, pygen/pygen_src/isa/riscv_instr.py
Ignoring the pygen output files.
=> Ignore log and asm file

src/isa/riscv_vector_instr.sv, src/isa/rv32v_instr.sv, src/riscv_amo_instr_lib.sv, src/riscv_instr_pkg.sv, src/riscv_load_store_instr_lib.sv, target/rv64gcv/testlist.yaml
=> Add vector AMO instruction support

pygen/pygen_src/isa/riscv_instr.py, pygen/pygen_src/riscv_instr_pkg.py
- Fix indentation Issue in generated assembly file
- Fix typo in extend_imm() function. 
- Fix imm_c constraint (Temporary Solution).
=> [Pygen] Fix minor Issues

pygen/pygen_src/riscv_instr_gen_config.py, pygen/pygen_src/riscv_instr_stream.py
=> Pygen_src: minor fix

src/riscv_privil_reg.sv
Fixes an issue brought to light by @vandanaprabhu in #636.
=> fix pmpcfg csr definitions

pygen/pygen_src/isa/riscv_instr_cov.py, pygen/pygen_src/riscv_instr_pkg.py, pygen/pygen_src/test/riscv_instr_cov_test.py
More methods will be added to complete the coverage test file.
=> Added methods to the coverage test file

pygen/pygen_src/riscv_asm_program_gen.py, pygen/pygen_src/riscv_instr_gen_config.py, pygen/pygen_src/riscv_instr_pkg.py, pygen/pygen_src/target/rv32i/riscv_core_setting.py
Add more functions of the **riscv_asm_gen_program.py** file to achieve the compilation and simulation of the generated assembly file.
Achieve simulation of the current assembly file in both SPIKE and OVPsim.
=> [Pygen]: Modify asm_program functions.

src/riscv_asm_program_gen.sv, src/riscv_pmp_cfg.sv
This patch adds in a new directed sequence of instructions placed
directly after the PMP setup.
This directed sequence will write randomized values to every `pmpaddr`
and `pmpcfg` CSR in order to test write accessibility (and spec
compliance). Correctness checking for this sequence is determined by
post-comparison with the ISS log, as per usual.
=> Add new PMP directed sequence

src/isa/riscv_amo_instr.sv
=> Fix AMO instruction constraint issue

pygen/pygen_src/isa/riscv_instr.py, pygen/pygen_src/riscv_asm_program_gen.py, pygen/pygen_src/riscv_defines.py, pygen/pygen_src/riscv_directed_instr_lib.py, pygen/pygen_src/riscv_instr_gen_config.py, pygen/pygen_src/riscv_instr_sequence.py, pygen/pygen_src/riscv_instr_stream.py, pygen/pygen_src/riscv_pseudo_instr.py, pygen/pygen_src/riscv_utils.py, pygen/pygen_src/test/riscv_instr_base_test.py
=> [Pygen]: Add directed instr

pygen/pygen_src/riscv_asm_program_gen.py, pygen/pygen_src/riscv_instr_gen_config.py
This PR fixes a few issues in riscv_asm_program_gen and riscv_instr_gen_config
=> [Pygen]: minor fixes

src/riscv_amo_instr_lib.sv, src/riscv_instr_stream.sv
=> Fix LR/SC sequence issue

pygen/pygen_src/isa/riscv_instr.py, pygen/pygen_src/riscv_asm_program_gen.py, pygen/pygen_src/riscv_instr_gen_config.py, pygen/pygen_src/riscv_instr_pkg.py, pygen/pygen_src/test/riscv_instr_base_test.py, run.py, yaml/simulator.yaml
This PR integrates pyflow instruction generator into the overall run flow and makes the required modifications on the pyflow instruction generator side.
=> [Pygen]: Pyflow integration

pygen/pygen_src/isa/riscv_instr.py, pygen/pygen_src/riscv_instr_gen_config.py, pygen/pygen_src/test/riscv_instr_base_test.py
This PR fixes minor issues that were generated after the merging of #688 with the overall end-to-end flow.
=> [Pygen]: Fix minor issues

cov.py, pygen/pygen_src/isa/riscv_cov_instr.py, pygen/pygen_src/riscv_instr_cover_group.py, pygen/pygen_src/test/riscv_instr_cov_test.py
This PR integrates functional coverage side of pyflow into cov.py and makes required modifications.
=> [PyFlow]: FC integration

pygen/pygen_src/isa/riscv_instr.py, pygen/pygen_src/riscv_asm_program_gen.py, pygen/pygen_src/riscv_data_page_gen.py, pygen/pygen_src/riscv_directed_instr_lib.py, pygen/pygen_src/riscv_instr_gen_config.py, pygen/pygen_src/riscv_instr_pkg.py, pygen/pygen_src/riscv_instr_sequence.py
This PR adds **riscv_data_page_gen, riscv_push_stack_instr** and **riscv_pop_stack_instr**
=> [Pygen]: Add riscv_data_page_gen

pygen/pygen_src/riscv_instr_cover_group.py
This PR significantly (~20X) improves performance of functional coverage (through changing the way that covergroups are instantiated & data are sampled).
=> [PyFlow]: Functional Coverage Performance Optimization

src/isa/riscv_vector_instr.sv
=> Fix solve...before... on non-rand variables issue

src/riscv_load_store_instr_lib.sv
=> Fix index offset constraint conflict

test/riscv_instr_cov_test.sv
=> Fix coverage issue for ml target

src/riscv_page_table_list.sv
=> Add sfence.vma after PTE process

test/riscv_instr_cov_test.sv
Fix #735 
The illegal instruction error is by default disabled as the trace CSV could have illegal instructions from error tests. Previously the error test intention is implied by the CSV name, which may not be true for all tests.  User can still enable illegal instruction error reporting by specifying runtime option +report_illegal_instr=1
=> Remove unintended errors in the coverage flow

pygen/pygen_src/isa/riscv_instr.py, pygen/pygen_src/riscv_asm_program_gen.py, pygen/pygen_src/riscv_instr_gen_config.py, pygen/pygen_src/riscv_instr_pkg.py, pygen/pygen_src/riscv_privileged_common_seq.py, pygen/pygen_src/target/rv32i/riscv_core_setting.py, pygen/pygen_src/target/rv32imc/riscv_core_setting.py, pygen/pygen_src/target/rv32imcb/riscv_core_setting.py, pygen/pygen_src/target/rv32imfdc/riscv_core_setting.py, pygen/pygen_src/test/riscv_instr_base_test.py, target/rv32imfdc/riscv_core_setting.sv
This PR adds the conversion of all the string comparison of riscv_core_setting fields to a python enum type.
This fix was needed in order to implement the previous TODO's related to processor configuration.
=> [Pygen] Fix minor issues.

src/riscv_privileged_common_seq.sv
=> Fix syntax issue

src/isa/riscv_floating_point_instr.sv
=> Add rounding mode support for floating point arithmetic instructions

src/isa/riscv_floating_point_instr.sv
=> Add a knob to use rounding mode from the instruction

pygen/pygen_src/riscv_asm_program_gen.py, pygen/pygen_src/riscv_signature_pkg.py
This PR adds the vector interrupt handler along with the riscv_signature_pkg class.
PS: Merge this after #769
=> [Pygen]: Add vector Interrupt handler

pygen/pygen_src/riscv_asm_program_gen.py, pygen/pygen_src/riscv_instr_gen_config.py, pygen/pygen_src/target/multi_harts/riscvOVPsim.ic, pygen/pygen_src/target/multi_harts/riscv_core_setting.py
This PR adds the support for multi_hart configuration along with fixing the issue related to rcs of riscv_gen_config class.
=> [Pygen] Add support for multi_harts

.github/workflows/metrics-regress.yml
CI currently fails due to some backend issue,
temporarily disable it on all PRs until a fix
is implemented.
=> [ci] temporarily disable CI flow

test/riscv_instr_cov_test.sv
=> Fix illegal opcode issue in the cov_test

target/ml/testlist.yaml
Signed-off-by: Udi Jonnalagadda <udij@google.com>
=> update ml/testlist.yaml to get better coverage

src/isa/riscv_compressed_instr.sv, src/isa/riscv_instr.sv
Fixed length of binary in riscv_instr.sv and riscv_compressed_instr.sv
=> Update var binary of convert2bin in riscv_instr.sv

run.py
=> [Pygen]: Add gen_timeout for PyFlow

pygen/pygen_src/README.md
=> [Pygen]: Add README.md for PyFlow

pygen/pygen_src/isa/riscv_cov_instr.py, pygen/pygen_src/riscv_instr_cover_group.py, pygen/pygen_src/riscv_instr_pkg.py, pygen/pygen_src/test/riscv_instr_cov_test.py
=> [Pygen]: Add coverage for RV32C instruction

pygen/pygen_src/isa/riscv_instr.py, pygen/pygen_src/isa/rv64c_instr.py, pygen/pygen_src/isa/rv64i_instr.py, pygen/pygen_src/isa/rv64m_instr.py, pygen/pygen_src/target/rv64imc/riscv_core_setting.py
This PR adds RV64IMC support for PyFlow.
=> [PyFlow]: Add support for RV64IMC

pygen/pygen_src/isa/rv64a_instr.py, pygen/pygen_src/isa/rv64d_instr.py, pygen/pygen_src/isa/rv64f_instr.py, pygen/pygen_src/target/rv64imafdc/riscv_core_setting.py, run.py, target/rv64imafdc/riscvOVPsim.ic, target/rv64imafdc/riscv_core_setting.sv, target/rv64imafdc/testlist.yaml
=> [PyFlow] Add support for RV64AFD

pygen/pygen_src/README.md, pygen/pygen_src/riscv_asm_program_gen.py, pygen/pygen_src/riscv_callstack_gen.py, pygen/pygen_src/riscv_directed_instr_lib.py, pygen/pygen_src/riscv_instr_gen_config.py, pygen/pygen_src/riscv_instr_sequence.py
This PR adds the support for sub_program in riscv-dv-pyflow.
=> [PyFlow]: Add support for sub_programs

pygen/pygen_src/riscv_instr_gen_config.py, pygen/pygen_src/riscv_loop_instr.py, pygen/pygen_src/riscv_utils.py
Creating a Draft PR for now.
In some cases getting an undesirable colon at the beginning of the instructions.
=> [Pygen]: Add riscv_loop_test

yaml/simulator.yaml
Includes a minor change to pass coverage related flags to xrun.
Signed-off-by: Canberk Topal <ctopal@lowrisc.org>
=> [XCelium] Enable coverage collection with XCelium

pygen/pygen_src/riscv_loop_instr.py
=> Fix broken loop test. #857

pygen/pygen_src/riscv_instr_pkg.py
=> [Pygen] Fix typo in mseccfg_reg_t class

src/riscv_pmp_cfg.sv
The problem that I was running into with machine mode lockdown (MML) and machine mode whitelist policy (MMWP) is that I needed the instructions under the `pmp_setup` label (eventually in PMP region 0) to be set to executable. Otherwise it would set `MSECCFG` and then trap on the instruction immediately after. However, we still want to set `MSECCFG` before configuring the PMP configs because some PMP setups are valid depending on the Smepmp mode.
My proposed solution is to change the `gen_pmp_instr` function to take these steps:
- Set address of region 0 before setting MSECCFG
- If  MML, initially set MSECCFG to MML=0, MMWP=0, RLB=1
- If  MML, set the config of region 0 to LXWR=1100 and TOR
- If MMWP, set the config of region 0 to LXWR=0111 and TOR
- If MML or MMWP, set requested MSECCFG …
=> [Smepmp] Fixes `gen_pmp_instr` when MML and MMWP are enabled

scripts/gen_csr_test.py, yaml/csr_template.yaml
There are other methods to approach this but I felt this would provide the maximum flexibility without over-complicating the CSR YAML format.
=> Gen csr improvements

src/riscv_asm_program_gen.sv
=> [pmp] No PMP exception handler when no PMP support

src/isa/riscv_csr_instr.sv
Where contraints allow a CSR to be both read and written read-only vs
read-write (and write-only) operation was effectively chosen by which
register or immediate was randomly chosen. This made read-only accesses
to such CSRs rare.
Now we explicitly choose to do a read or a read-write with an explicit
random bit that is solved before the register or immediate.
Even with this change the distruibution skews to read-write operation as
the CSRRW and CSRRWI instructions cannot be read-only and that is chosen
independently of the explicit read-only/read-write decision introduced
by this commit. Fixing this so we get a 50/50 distribution of
read-only/read-write is significantly more complex but isn't required as
the read-only case is now sufficiently common.
This also allows the removal of the …
=> Tweak CSR constraints for more even read/write distribution

src/isa/riscv_csr_instr.sv, src/riscv_instr_pkg.sv
This fixes VCS compilation errors about complex assignments 
Signed-off-by: Canberk Topal <ctopal@lowrisc.org>
@GregAC @hcallahan-lowrisc @weicaiyang PTAL
=> [sv] Explicit type casting for VCS compability

src/isa/riscv_compressed_instr.sv
Signed-off-by: Henrik Fegran <Henrik.Fegran@silabs.com>
=> Fix for issue #826, illegal rs1 in C_JALR

src/isa/riscv_csr_instr.sv, yaml/simulator.yaml
This PR fixes the support for Questa
also fixes this Issue
https://github.com/chipsalliance/riscv-dv/issues/914
=> Support for Questa

src/riscv_pmp_cfg.sv
Proposed fix for the following comment: https://github.com/chipsalliance/riscv-dv/commit/31a73ff26a0cd26dd3033ae29fa3df0aa9d28b64#r94906388
@JJ-Gaisler
=> [pmp] Remove MSECCFG reads from trap handler when Smepmp is disabled
