chipsalliance/riscv-dv

README.md, src/riscv_instr_pkg.sv, src/riscv_page_table_list.sv
Reverts google/riscv-dv#8 because CLA not signed
=> Revert "Fix typos/grammar in README & code comments"

run.py
I make PR to give error for mutually exclusive between `-co`, and `-so` argument
=> Give error for mutually exclusive between -co, and -so argument

yaml/csr_template.yaml, yaml/iss.yaml, yaml/simulator.yaml, yaml/testlist.yaml
It seems a global search-replace broke these URLs, fixing them.
=> Fix license URLs in comments

scripts/spike_log_to_trace_csv.py
Spike has a forthcoming patch which additionally adds memory writes
to the commit log. AMO's may be logged wiht a commited register
and a memory operation. Tightening up the regex will ensure that
the extra logging won't break instruction trace comparison against
spike.
See https://github.com/riscv/riscv-isa-sim/pull/324
=> Tighten up regex in spike log tracer.

src/riscv_asm_program_gen.sv, src/riscv_instr_gen_config.sv
=> Add a bare program mode

scripts/link.ld, setting/riscv_core_setting.sv, src/riscv_amo_instr_lib.sv, src/riscv_asm_program_gen.sv, src/riscv_data_page_gen.sv, src/riscv_directed_instr_lib.sv, src/riscv_instr_gen_config.sv, src/riscv_instr_pkg.sv, src/riscv_instr_stream.sv, src/riscv_load_store_instr_lib.sv, src/riscv_page_table.sv, test/riscv_instr_test_lib.sv, yaml/testlist.yaml
- Allow user to specify the range of each memory region
- Assign a separate section for each memory region so that it can be linked to match system memory map.
- Refactor load/store/amo test
update #129
=> Re-organize data page generation

scripts/gen_csr_test.py, setting/riscv_core_setting.sv, src/riscv_asm_program_gen.sv, src/riscv_instr_gen_config.sv, src/riscv_instr_pkg.sv, src/riscv_privil_reg.sv, src/riscv_privileged_common_seq.sv, src/riscv_reg.sv, src/riscv_signature_pkg.sv
-Add handshakes to write xIE, xIP, and xCAUSE to the testbench on exceptions and interrupts for more checking analysis
- Removed all csr WIRI fields as per the spec
- make WPRI csr fields writable, to allow for platform-specific csr configurations
- randomize csr generation, in particular the interrupt enable bits in xSTATUS and xIE
=> Interrupt test integration

src/riscv_directed_instr_lib.sv
Avoid skipping a large portion of the program
=> Lower the percentage of JAL instruction

yaml/iss.yaml
Spike now needs the --log-commits option passed to it to generate commit
info in the log.
=> Fix spike arguments to generate commit log

src/riscv_asm_program_gen.sv, src/riscv_instr_gen_config.sv, src/riscv_instr_stream.sv
-Enable full configuration of ebreak generation - all permutations of ebreak in main program and debug program are now possible.
-For the debug_ebreak_test in particular, move the DCSR and DPC handshakes within the stack push/pop operations to avoid corrupting program state
=> Add more ebreak generation control

src/riscv_asm_program_gen.sv, src/riscv_instr_base.sv, src/riscv_instr_gen_config.sv, src/riscv_instr_stream.sv, src/riscv_rand_instr.sv, target/rv64gc/testlist.yaml, yaml/base_testlist.yaml
- All invalid (e.g. higher privilege level) CSRs are added to a queue in `cfg` on generator initialization, making constraints much more simplified
=> Add directed stream to access higher privilege CSRs

.gitignore, README.md, qrun_option.f, yaml/simulator.yaml
Hi, Mentor released a new feature named `qrun`. The qrun simplifies the use of QuestaSIM by automatically combining the compile, optimize, and simulate functions into a single step. The qrun command has these major features:
1. All tool arguments and source files go on the same qrun command line.
2. All vlog, vopt, vsim arguments go on the qrun command line unmodified.
3. It is able to support two or three step flows.
4. Provides pre-built flows for coverage, debug, UVM and other flows. No need to construct arguments for multiple tools.
5. If you re-invoke the same command with no source code or command line argument changes, then the qrun command skips compilation and optimization and invokes vsim.
You can read reference information of qrun at: …
=> Adding support qrun simulator

README.md, requirements.txt
Hi,
I add requirements for install dependencies into `requirements.txt`. It is easy to install by pip3.
=> Add requirements for install dependencies

src/riscv_loop_instr.sv, src/riscv_rand_instr.sv
Fix bug introduced by #321 that would cause instructions acting as loop branch targets to access completely random CSRs
=> Fix CSR randomization bug when generating loops

cov.py, run.py, scripts/gen_csr_test.py, scripts/lib.py, scripts/ovpsim_log_to_trace_csv.py, scripts/riscv_trace_csv.py
also make ovpsim parsing script indentations 2 spaces, to avoid mixing 2-space and 4-space indents in one file
=> Fix list access exception thrown when parsing ovpsim illegal instruction

src/riscv_asm_program_gen.sv, src/riscv_instr_gen_config.sv
set xSTATUS.xIE in trap handler to enable receiving nested interrupts
=> enable nested traps

cov.py, run.py, scripts/lib.py
I make PR to clean the output directory by default.
Do not clean the output directory may have effect on expected output because of the output of previous run. Similarly for cov.py, if people want to use the output of previous runs, it can be specified by "--noclean" switch.
=> Cleaning the output directory by default. Using "--noclean" for using the output of previous runs

run.py
I make PR to generate error message for `gcc` compile when it cannot find assembly files.
=> Generate error for gcc compile when it cannot find assembly files

scripts/lib.py
For issue #256 . Spike is invoked by `run_cmd` function. So, add try-except for handling KeyboardInterrupt can resolve it when user uses Ctrl-C.
=> Add handling KeyboardInterrupt for run_cmd and run_parallel_cmd

cov.py
Running: $ cov
Tue, 07 Jan 2020 10:47:27 INFO     Creating output directory: cov_out_2020-01-07
Tue, 07 Jan 2020 10:47:27 INFO     Processing trace log under None
Traceback (most recent call last):
File "/home/danghai/.local/bin/cov", line 11, in <module>
load_entry_point('riscv-dv', 'console_scripts', 'cov')()
File "/home/danghai/hhoangda/riscv-dv/cov.py", line 289, in main
collect_cov(output_dir, cfg ,cwd)
File "/home/danghai/hhoangda/riscv-dv/cov.py", line 127, in collect_cov
if not os.path.isdir(argv.dir) or not os.listdir(argv.dir):
File "/usr/lib/python3.6/genericpath.py", line 42, in isdir
st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
=> Fix running cov without arguments

cov.py, run.py, scripts/lib.py
I make PR to add `run_cmd_output` for reporting all debug command lines.
=> Add run_cmd_output for reporting all debug command lines

run.py
also make `noclean = True` as the default value to avoid unnecessary deletion of output directories
=> fix matched_list and directed_list size comparisons

run.py
Because it does not run command when specified "-debug" switch, it cannot generate the csv file. It has error for comparing the csv file. I mean:
$ run --test riscv_arithmetic_basic_test --iss=spike,ovpsim --debug debug.log
```
sed: can't read out_2020-01-21/spike_sim/riscv_arithmetic_basic_test.0.log: No such file or directory
sed: can't read out_2020-01-21/spike_sim/riscv_arithmetic_basic_test.0.log: No such file or directory
Traceback (most recent call last):
File "/home/danghai/.local/bin/run", line 11, in <module>
load_entry_point('riscv-dv', 'console_scripts', 'run')()
File "/home/danghai/hhoangda/riscv-dv/run.py", line 780, in main
args.exp, args.debug)
File "/home/danghai/hhoangda/riscv-dv/run.py", line 504, in iss_cmp
compare_iss_log(iss_list, log_list, report, …
```
=> run.py: Do not compare csv file when specified -debug switch

qrun_option.f
irun has `-access +rwc`, qrun is missing this option.
=> Qrun is missing -access=wrc option

src/dv_defines.svh, src/riscv_asm_program_gen.sv, src/riscv_instr_gen_config.sv, src/riscv_instr_pkg.sv, src/riscv_pmp_cfg.sv, target/ml/riscv_core_setting.sv, target/rv32i/riscv_core_setting.sv, target/rv32imc/riscv_core_setting.sv, target/rv64gc/riscv_core_setting.sv, target/rv64gcv/riscv_core_setting.sv, target/rv64imc/riscv_core_setting.sv
- added some new randomization macros for ease of use
- the uvm_cmdline_processor instance has been moved to the riscv_instr_pkg to allow the command line parsing functions to be used by various configuration objects as needed
- basic pmp configuration object added - with just the default values for now
=> Add pmp configuration object

README.md, src/isa/riscv_compressed_instr.sv, src/isa/riscv_instr.sv, src/riscv_asm_program_gen.sv, src/riscv_debug_rom_gen.sv, src/riscv_defines.svh, src/riscv_illegal_instr.sv, src/riscv_instr_cov_item.sv, src/riscv_instr_gen_config.sv, src/riscv_instr_pkg.sv, src/riscv_page_table_entry.sv, src/riscv_page_table_list.sv, verilog_style/build-verible.sh, verilog_style/exclude_filelist.f, verilog_style/run.sh
1. verilog_style/build-verible.sh to install the tool
2. tool reports uncorrect syntax error on some files, list them at
verilog_style/exclude_filelist.f and skip checking on them
3. usage:
- install command: ./verilog_style/build-verible.sh
- style check run command: ./verilog_style/run.sh
=> Add style check

src/riscv_instr_gen_config.sv, src/riscv_load_store_instr_lib.sv, test/riscv_instr_test_lib.sv
According to the SV 1800-2017 standard using non random variable as a solve...before argument is not allowed. In two cases - for variable "init_privileged_mode" and "use_sp_as_rs1 " the randomization possibilities are disabled by rand_mode(0) but the "solve...before" constraint is still active causing compilation problems. To fix that the "solve...before" constraint should be divided and the ordering part should be disabled before randomization. After randomization, if it is necessary the "solve...before" constraint can be re-enabled.
Kind regards,
Darek
=> The "solve...before" constraints should be modified.

scripts/gen_csr_test.py
Eliminate passing in the signature_addr without the `0x` prefix, as per discussion in https://github.com/lowRISC/ibex/pull/620
=> minor change to signature_addr passed to generator

scripts/spike_log_to_trace_csv.py
Yesterday, I spent half an hour getting very confused about why my
Spike logs (which didn't some magic lines) were getting replaced with
the empty file when I tried to use them as inputs to this script.
This patch replaces the 'sed -i' invocations with equivalent logic in
the actual Python. It also factors out the code that parses the trace
from the code that uses it, which I think makes things a bit more
obvious.
Finally, the patch adds lots of comments, explaining the control flow:
when writing this, I really struggled to figure out what the existing
code was trying to do with things like WFI and ECALL instructions and
architectural updates. Hopefully, this is much clearer now.
Other than not rewriting input files, there are two known changes
caused by this patch. Firstly, the previous …
=> Don't change input file in spike_log_to_trace_csv.py

run.py, yaml/simulator.yaml
Renames coverage database output directories to `test_<test_id>` from `test_<seed>` to provide uniquification of names for use cases where a same seed value is passed to every test iteration (like in Ibex environment).
=> [cov] tag coverage database directories with <test_id>

run.py, src/isa/riscv_b_instr.sv, src/isa/riscv_compressed_instr.sv, src/isa/riscv_floating_point_instr.sv, src/isa/riscv_instr.sv, src/isa/riscv_vector_instr.sv, src/riscv_asm_program_gen.sv, src/riscv_instr_gen_config.sv, src/riscv_instr_sequence.sv, src/riscv_page_table_entry.sv, src/riscv_pmp_cfg.sv, verilog_style/exclude_filelist.f
1. Add to run style check when you run sim
2. Update codes for new rule below in latest style tool
- Explicitly define a default case for every case statement
3. Update exclude_filelist as a tool bug has been fixed
Everyone needs to run ./verilog_style/build-verible.sh to get the latest
version
Signed-off-by: Weicai Yang <weicai@google.com>
=> Update style check

src/riscv_asm_program_gen.sv, src/riscv_instr_gen_config.sv, src/riscv_instr_pkg.sv, src/riscv_pmp_cfg.sv
- add a pmp_min_address value, which is the address that will get stored into pmpaddr0, this value will be set to an address just after the <main> label, to ensure that the entirety of the initialization routines are safe from PMP faults
- move the init_[user/machine/supervisor]_mode routine generation into this safe zone at the beginning of the program
- calculate remaining pmpaddr default values as offsets from the pmp_min_address to make sure that the address space bounded by 0 and pmp_max_address is evenly split between all enabled pmp configuration registers
=> more tightly constrain pmpaddr values

target/rv32imcb/riscvOVPsim.ic
ovpsim can support b-ext now #520
=> Fix a typo in riscvOVPsim

target/ml/riscv_core_setting.sv, target/multi_harts/riscv_core_setting.sv, target/rv32i/riscv_core_setting.sv, target/rv32imc/riscv_core_setting.sv, target/rv32imcb/riscv_core_setting.sv, target/rv64gc/riscv_core_setting.sv, target/rv64gcv/riscv_core_setting.sv, target/rv64imc/riscv_core_setting.sv
Parameters should be constant at elaboration time. Creating parameter of dynamic array type (which main idea it to be dynamic at runtime) is not clearly defined as legal by LRM. 
Please change it to a const array - it should express expected behaviour better.
=> Change dynamic array parameters to const.

src/riscv_asm_program_gen.sv
In most cases the gen_function() use variable (str, instr) as second argument. The code will be probably more readable if this style is used also in this place.
=> Unify the gen_section() function calls

src/riscv_asm_program_gen.sv, src/riscv_instr_gen_config.sv, src/riscv_instr_pkg.sv, src/riscv_pmp_cfg.sv
Load the address of `<main>` section into `pmpaddr0` CSR, and use an offset scheme to configure all other enabled `pmpaddr` CSRs relative to the first one.
=> [pmp] Relative addressing scheme to configure pmpaddr

src/riscv_instr_pkg.sv, src/riscv_pmp_cfg.sv
This is a relatively straightforward PR with the initial steps to convert from passing in a "max_offset" from the command line (which is pretty unintuitive from the user perspective) to passing in a maximum limit address, to eventually being able to assign code sections to pmp regions from the command line.
For now, we take the first step of adding back functionality to specify a physical address from the cmdline separately from the default assigned offset - if specified, this address will take priority over the offset when configuring pmp CSRs.
=> specify physical pmp addresses from cmdline

src/riscv_asm_program_gen.sv, src/riscv_instr_gen_config.sv, src/riscv_pmp_cfg.sv
This PR adds new functionality to the PMP configuration object to enable generation of a custom PMP fault handling routine, that will loop through each `pmpaddr/pmpcfg` CSR pair, match up the correct CSRs to the faulting address, then "fix" the configuration settings by enabling the appropriate access permissions.
For example, say `pmpaddr0` is set to `0x80002000`, and its corresponding 8-bit access configuration fields are set such that the address matching scheme is `TOR` and all instruction fetches are disabled. If an instruction fetch to `0x80001FFC` is made, a PMP fault will occur, and the core will jump to the generated instruction fetch exception handler. Assuming `mepc` is not modified, after executing the handler the core will jump back to the same address that caused the trap, …
=> update PMP exception handlers to 'fix' config CSRs

src/isa/riscv_instr.sv
currently, the combination of `+no_ebreak=0` and `+disable_compressed_instr=1` will incorrectly generate compressed ebreak instructions - this PR fixes that issue.
=> fix bug with compressed ebreak generation

src/isa/riscv_b_instr.sv, src/riscv_asm_program_gen.sv, src/riscv_instr_gen_config.sv, src/riscv_instr_pkg.sv
For issue #572
also clean up some tabs
=>  Move `sext.b/h` bitmanip instructions to ZB_TMP

run.py, scripts/lib.py
*Note: I've edited this summary to match the version pushed up as `5dbfc25`.*
The `--seed_start` argument allows you to say "Please use the following
seed for the first iteration of each test. If you run more iterations
than one, increment the seed accordingly".
The idea is that some top-level program (for example Ibex's core_ibex
UVM test code) can pick a seed, possibly randomly, and then run many
tests using the same seeds for test generation (here) and test
execution (passed to the simulator that runs them).
We could implement that by generating a YAML file each time and
passing it with `--seed_yaml`, but that seems unnecessarily complicated.
While touching the seed handling code, I've also added checks for
various silly combinations of arguments that used to be possible.
- If you …
=> Add --seed_start argument and tidy up seed handling

src/riscv_instr_gen_config.sv
Adds a `set_mstatus_mprv` commandline configuration bit that can be used to set `mstatus.mprv`, required for PMP tests - this bit is not set by default.
If `set_mstatus_mprv` is not set, the value of `mstatus.mprv` is randomized. This is okay because in cores that do not support this feature, the hardware masks this field to 0.
=> add cmdline configuration of mstatus.mprv

src/riscv_pmp_cfg.sv
This PR contains three minor patches (each with its own commit):
1) A patch to a previously introduced bug dealing with scenarios where no matches are seen in the exception handler - in this situation we need to jump to `<test_done>` regardless of privilege mode.
2) An update that disables randomization of `pmp_num_regions` if it is specified from the command line.
3) An update to address mode constraints - if the granularity is 0, we cannot use NAPOT matching mode.
=> various PMP exception handler fixes

test/riscv_instr_test_lib.sv
These hardcoded config values are no longer needed for ML testing, they now interfere with randomly generated config parameters and can cause esoteric failures.
=> Fixes for ML tests

.flake8, .travis.yml, requirements.txt
I add flake8 check for pygen. You can turn on `travis CI` to catch these errors. It currently complains a lot errors:
https://travis-ci.org/github/danghai/riscv-dv/jobs/694103331
You can add `.flake8` if you want to ignore the rules.
=> Add flake8 check for pygen

src/riscv_asm_program_gen.sv, src/riscv_instr_sequence.sv
When enabling PMP settings, `<main>` section needs to be 4-byte aligned - if it is not there is a chance that the last instruction before `<main>` will cause a PMP exception (if uncompressed).
This PR also scopes all references to `support_pmp` with `riscv_instr_pkg::` just for clarity, this does not functionally change anything.
=> make <main> 4-byte aligned when enabling PMP

src/riscv_load_store_instr_lib.sv
=> Fix vector unit strided load/store instruction stream name

yaml/simulator.yaml
Extra switch has been added to the Aldec Riviera-PRO compiler command line arguments to avoid potential compilation problems.
=> Aldec Riviera-PRO compiler command line arguments modified.

pygen/pygen_src/isa/riscv_instr.py, pygen/pygen_src/riscv_instr_stream.py
The issue with post_randomize() was resolved in <https://github.com/fvutils/pyvsc/issues/17>.
Hence, the issue with **None** immediate value #642 is also resolved after getting support from PyVSC in its latest PyPI release.
=> [Pygen] Fix post_randomize issue

src/riscv_asm_program_gen.sv, src/riscv_debug_rom_gen.sv, src/riscv_illegal_instr.sv, src/riscv_instr_pkg.sv, target/ml/riscv_core_setting.sv, target/multi_harts/riscv_core_setting.sv, target/rv32i/riscv_core_setting.sv, target/rv32imc/riscv_core_setting.sv, target/rv32imcb/riscv_core_setting.sv, target/rv64gc/riscv_core_setting.sv, target/rv64gcv/riscv_core_setting.sv, target/rv64imc/riscv_core_setting.sv, target/rv64imcb/riscv_core_setting.sv
The first commit adds initial support for custom CSRs - users can specify them in `custom_csrs` in the `riscv_core_setting.sv`.
The second commit is just some cleanups in various places through the generator to remove hardcoded CSR names and replace them with the enumerated values.
=> initial custom CSR support

src/riscv_illegal_instr.sv
One of the opcodes in `b_extension_c` constraint of `riscv_illegal_instr` is incorrect, causing some of the generated illegal instructions to actually be valid B-extension instructions.
Also added a TODO to enable creation of illegal B-extension instructions as well, instead of the current approach of excluding them entirely.
=> Fix opcode in b_extension_c constraint

src/isa/riscv_vector_instr.sv
According to SV standard (1800-2017, p.505):
> — Constraints can be any SystemVerilog expression with variables and constants of integral type (e.g.,
> bit, reg, logic, integer, enum, packed struct)"
The constraint:
https://github.com/google/riscv-dv/blob/10a7a1094d49c0e86c0b75e11894bfd241364ad7/src/isa/riscv_vector_instr.sv#L185-L186
uses comparison of string variable with literal which shouldn't be allowed.
The solution of the problem can be a replacing of the comparison with a function call. The actual comparison can be moved to the function as proposed in PR.
=> Constraints should contain only integral types - fix error in riscv_vector_instr.sv

pygen/pygen_src/riscv_instr_gen_config.py
Just adding the constraint for GPR.
`not_inside` is not yet supported in PyVSC when we declare a list of enum types of fix size as `vsc.rand_list_t(vsc.enum_t(riscv_reg_t), sz =4)`
=> Add gpr_c constraint

src/riscv_pmp_cfg.sv
In the directed PMP CSR write sequence, another constraint is needed to ensure the combination of R=0/W=1 does not occur, as this is undefined/unsupported behavior in the current spec.
=> update directed pmp sequence constraint

src/isa/riscv_instr_cov.svh
Addresses an issue brought up by @hodjat91.
This `if...` statement will never be reached, as there is a previous check in the method to check whether `value == 0`, thus it can be removed without any side effects.
=> remove unreachable if statement

pygen/pygen_src/isa/riscv_cov_instr.py, pygen/pygen_src/riscv_instr_cover_group.py, pygen/pygen_src/riscv_instr_pkg.py, pygen/pygen_src/test/riscv_instr_cov_test.py
This PR:
- Adds riscv_instr_cover_group file
- Confirms riscv_instr_cov_test (parser) script is up and running fine
- Initializes the registers to 0 in their first gpr_state access (for ovpsim output log)
=> [pygen]: Adds riscv_instr_cover_group file

src/riscv_pmp_cfg.sv
We don't need to add 1 to get the upper bound of this constraint as `inside` constraint is inclusive, this led to some edge case randomization failures.
=> fix pmp offset constraint

pygen/pygen_src/riscv_instr_cover_group.py, pygen/pygen_src/riscv_instr_pkg.py, pygen/pygen_src/test/riscv_instr_cov_test.py
This PR:
- Adds support for coverage report visualization (by storing the coverage results in XML format to be read by pyucis-viewer)
- Adds CSR, opcode, rv32i_misc, and mepc_alignment covergroups
=> Coverage report visualization supported + Few covergroups are added to complete RV32I CGs

scripts/gen_csr_test.py
RISC-V DV is mostly Python 3.5-compatible, with the exception of the use
of f strings in gen_csr_test.py. Replace those with Python
3.5-compatible `.format()` formatting.
=> Remove f strings for Python 3.5-compatibility

pygen/pygen_src/riscv_instr_stream.py
Fixes a subtle bug in ebreak generation that would prevent it from being
generated in the debug ROM under a specific parameter combination.
Mirrors #689.
Signed-off-by: Udi Jonnalagadda <udij@google.com>
=> [pygen/riscv_instr_stream] Fix ebreak generation

src/riscv_instr_stream.sv
Fixes a small issue that caused ebreak instructions to incorrectly not be generated under the right set of config options.
Signed-off-by: Udi Jonnalagadda <udij@google.com>
=> fix ebreak generation bug

target/ml/riscv_core_setting.sv, target/multi_harts/riscv_core_setting.sv, target/rv32i/riscv_core_setting.sv, target/rv32imc/riscv_core_setting.sv, target/rv32imc_sv32/riscv_core_setting.sv, target/rv32imcb/riscv_core_setting.sv, target/rv64gc/riscv_core_setting.sv, target/rv64gcv/riscv_core_setting.sv, target/rv64imc/riscv_core_setting.sv, target/rv64imcb/riscv_core_setting.sv
There "initial custom CSR support" commit introduced an empty constant "custom_csr":
https://github.com/google/riscv-dv/blob/0645eeaf3e1cd5927c32372b3ae142323ca3e9e8/target/rv32imc/riscv_core_setting.sv#L117-L123
The initialization of a constant variable with the empty array concatenation expression causes compilation problem on some tools, e.g. Riviera-PRO. 
It seems that this empty const variable is not used in the generator code - is it really necessary? The creation of empty const array is a little strange - what is a reason for creation of such variable?
This PR contains a workaround for Riviera-PRO that is identical as this  already existing for DSIM.
=> Workaround of the SV compilation problem caused by assigning the const array variable with the empty concatenation.

cov.py, run.py, scripts/gen_csr_test.py, scripts/instr_trace_compare.py, scripts/lib.py, scripts/ovpsim_log_to_trace_csv.py, scripts/riscv_trace_csv.py, scripts/sail_log_to_trace_csv.py, scripts/spike_log_to_trace_csv.py, scripts/whisper_log_trace_csv.py
This PR converts the python codes in riscv-dv repo to be PEP8 compliant (PR also contains other minor fixes).
=> Convert python codes to be PEP8 compliant

src/riscv_asm_program_gen.sv, src/riscv_pmp_cfg.sv
From #709, it appears there is an issue jumping to `init_machine_mode`
when generating a large (200k instructions) program.
This is because we currently use a standard `j` instruction to do the
jump which only has a 20-bit address range, so this range is exceeded in
a program of this size.
Similar issues arise when jumping to `test_done` and `write_tohost` from 
various exception handlers.
The solution is as follows:
1) Move the `init_[m/s/u]_mode` section to the top of the program to
prevent us from having to jump there in the first place - this does not
cause any side effects.
2) Change the jump mechanisms to `test_done` and `write_tohost` from `j test_done` to
preloading the address of `test_done` into a register and using a `jalr`
instruction to jump to this address - this allows us …
=> fix jumps to `test_done` and `init_[m/s/u]_mode`

target/rv64gcv/testlist.yaml
Update testlist to excluding all non machine mode test for RV64GCV target. Only machine mode is enabled for this target currently.
Fix #700
=> Fix invalid CSR test for RV64GCV target

src/riscv_debug_rom_gen.sv
The debug ROM is assembled with the sub-routines directly below the main
code section. The program is thus able to run straight through into the
sub-routine without there ever being a jalr into that sub-routine. That
means the return address for the sub-routine is undefined, and the
program jumps to a bogus address when the sub-routine returns.
This fix forces the main debug program to end (by jumping to debug_end)
and not just run on into the sub-routines, similarly to how the main
(non-debug) program works.
Signed-off-by: Tom Roberts <tomroberts@lowrisc.org>
=> debug_rom_gen: Fix return address issue

scripts/lib.py, scripts/ovpsim_log_to_trace_csv.py, scripts/spike_log_to_trace_csv.py, src/isa/riscv_instr_cov.svh
This PR does 2 main things to the functional coverage flow
1) Allows the .csv conversion scripts to recognize bit-manipulation pseudo-instructions - currently none are recognized so coverage failures are fairly common.
2) Changes how the 'operand' field of the output CSV is formatted.
Currently for any instructions that have an address (e.g. `rd, rs1(imm)`), the operands are structured as `rd,imm,rs1` in the output CSV file. This doesn't align with how the spec structures operands for these sorts of instructions, so this patch rearranges the operands such that they are displayed as `rd,rs1,imm` in the output CSV.
This has the side effect of standardizing how the CSVs are parsed among Spike, OVPsim, and any cores using riscv-dv (like Ibex).
=> coverage flow updates

yaml/simulator.yaml
VCS includes smart quotes in some DPI code, making G++ blow up during
compilation.
As a result we need to pass in -fno-extended-identifiers to tell G++ to
pretend that everything is ASCII and not error out during compilation.
Primary author: @rswarbrick
Co-author: @udinator
=> add VCS compile option for unicode

src/isa/riscv_floating_point_instr.sv
the form for `<instr> <reg> <imm>(<reg>)` instruction in CSV
is changed, updated accordingly
Signed-off-by: Weicai Yang <weicai@google.com>
=> Fix #751 for floating point coverage

scripts/spike_log_to_trace_csv.py
Spike recently changed their log format, adding "`core 0:`" to some lines where it wasn't before. This broke the log-to-csv conversion script (see #742).
I have tested this with a small number of programs and the output CSV is now identical with both the old and new trace formats.
**However** I'm still working towards getting riscv-dv set up for the first time, so I may not have seen some of the more-exotic trace contents. I'd appreciate someone taking a careful look at my changes. In particular, should the `core 0:` phrase be added to any of the other regular expressions?
=> Add support for new Spike trace format

yaml/simulator.yaml
This doesn't seem to be supported by at least Questa 2020.03 (see
issue #780). I don't have a Questa licence or manual locally, but it
looks like this is an Xcelium flag. Maybe it was supported by other
Questa versions as a compatibility shim? If we need to allow the
equivalent access, I think the argument is "+acc", but I'm not
convinced it's needed at all, so suggest removing it entirely.
Fixes #780.
=> [questa] Remove -access=rwc from vlog command line arguments

src/riscv_illegal_instr.sv
=> Avoid generating hint instruction when RV32C is turned off

.github/workflows/metrics-regress.yml, .metrics.json, scripts/genMetricsList.py, scripts/metrics-regress.py, yaml/iss.yaml
metrics-regress.yml:
* Changes to work with pull requests. The `pull_request_target` event is able to access secret variables, however the event is still commented out while Metrics adds support for pulling the special branch created by a GitHub PR.
.metrics.json:
* Changes to use spike instead of OVPsim. The ibex-toolchain:v2 docker image contains spike as well as the lowRISC rv32imc toolchain.
genMetricsList.py:
* use spike instead of OVPsim
metrics-regress.py:
* Changes to work with pull requests. Create a git reference for the pull request branch and send this to Metrics.
* Fix lint errors
* Display complete message returned by Metrics API in case of error
iss.yml
* Change the name of the Imperas ISS executable. riscvOVPsimPlus is now required.
=> Update scripts for Metrics CI regression

scripts/lib.py
Report job progress like "1/2" and "2/2" instead of "0/2" and "1/2", as
it was done before.
Only a cosmetic change.
=> Improve status reporting

pygen/pygen_src/isa/riscv_cov_instr.py, pygen/pygen_src/isa/riscv_instr.py, src/isa/riscv_instr.sv
Previous setting caused sign extension of the second-last bit of the immediates for instructions such as JALR.
Signed-off-by: Henrik Fegran <Henrik.Fegran@silabs.com>
=> Fixed wrong length of I, S, B-type immediates

src/riscv_privileged_common_seq.sv
MIE is explicitly set before mret is called, leading to potential infinite loop in case of an interrupt between interrupt enable and mret. Instead taken care of by MPIE as per Riscv-spec (Fix for issue #778 )
Signed-off-by: Henrik Fegran <Henrik.Fegran@silabs.com>
=> Issue #778 fix, change mie behavior in setup_mmode_reg

pygen/pygen_src/isa/riscv_instr.py
Override the inbuilt deepcopy method to improve the performance to some extent.
=> [Pygen]: Override deepcopy method

src/isa/riscv_zbb_instr.sv, src/isa/riscv_zbs_instr.sv
These >100 char lines cause issues in OpenTitan when vendoring in Ibex due to our Verible style linter.
Signed-off-by: Michael Schaffner <msf@google.com>
=> [style] Break long lines in newly added files

run.py
Fix typo in run.py script.
Signed-off-by: aneels3
=> Fix typo in run.py

pygen/pygen_src/test/riscv_instr_base_test.py
When running PyGen (Python 3.6 on Centos8), exceptions encountered by generation sub-processes result in the Python script hanging instead of exiting with an error. This PR intercepts exceptions in generation sub-processes and propagates an error indicator back to the generation script.
Signed-off-by: Matthew Ballance <matt.ballance@gmail.com>
=> Trap and report exceptions encountered in sub-processes and propagate errors

run.py
Newer versions of Spike need the required bitmanip sub-extensions to be specified separately in the ISA string as `_Zba_Zbb_Zbc_Zbc_Xbitmanip` (where `_Xbitmanip` comprises all sub-extensions not part of v.1.0.0 but remaining in draft v.0.9.4) instead of just `b`. Previously, `run.py` would print an error message when parsing such an ISA string but still call
Spike with the correct arguments which is confusing.
With this commit, `run.py` is modified to accept such ISA strings and not print the error message.
=> Allow for underscores and capital letters in ISA for ISS

pygen/pygen_src/riscv_instr_pkg.py, src/riscv_instr_pkg.sv, src/riscv_pmp_cfg.sv, src/riscv_privil_reg.sv, target/ml/riscv_core_setting.sv, target/multi_harts/riscv_core_setting.sv, target/rv32i/riscv_core_setting.sv, target/rv32imafdc/riscv_core_setting.sv, target/rv32imc/riscv_core_setting.sv, target/rv32imc_sv32/riscv_core_setting.sv, target/rv32imcb/riscv_core_setting.sv, target/rv64gc/riscv_core_setting.sv, target/rv64gcv/riscv_core_setting.sv, target/rv64imafdc/riscv_core_setting.sv, target/rv64imc/riscv_core_setting.sv, target/rv64imcb/riscv_core_setting.sv
This PR adds basic support for the mseccfg CSR required for ePMP. Similar to the actual PMP configuration:
- the desired configuration for mseccfg can be provided using an argument, e.g. `+mseccfg=MML:0,MMWP:0,RLB:1`.
- if randomization is turned on, it's still possible to force the bits of `mseccfg` partially or completely using this argument.
The CSR is only configured if the bit `support_epmp` in `riscv_core_setting.sv` is set to 1.
=> [epmp] Add support for mseccfg CSR

scripts/lib.py
I propose a solution for a problem I found concerning the management of jobs that reach the timeout threshold.
Indeed, if the job creates child processes, they are not killed by the current management.
According to python docs, the fix works only on linux environment, It should works as before on windows thanks to try/except
=> lib.py, launch process in new session to fix timeout issue

src/isa/riscv_compressed_instr.sv, src/isa/riscv_floating_point_instr.sv, src/riscv_defines.svh
This PR fixes the #819 issue related to compressed floating-point instructions which require floating-point registers as operands.
Changes are being made for both Single and Double floating-point load and store instructions.
=> Compressed floating point  load-store instruction to have FPR as operands.

pygen/pygen_src/riscv_instr_gen_config.py, src/riscv_instr_gen_config.sv
This commit allows the case because if mstatus.tw is low, WFI behaviour
will not change regarding the mode. If it's set to one, it will act like
an illegal instruction. That is also not a problem because we already
generate illegal instruction handler inside gen_all_trap_handler method.
Signed-off-by: Canberk Topal <ctopal@lowrisc.org>
=> Allow for WFI in User Mode

src/riscv_asm_program_gen.sv, src/riscv_pmp_cfg.sv
By default PMP setup is included in every test which sets up a full set
of PMP regions. A test may wish to have full access to all of memory to
ensure there are no PMP failures.  This knob suppresses the general PMP
setup generation and instead generates a setup with a single region
giving full access to all of memory.
=> [pmp] Add knob to suppress PMP setup code

src/isa/riscv_instr.sv, src/riscv_instr_gen_config.sv
Adding ECALL to the main randomized body allows us to get coverage over this instruction, but requires you to rethink how the test_done mechanism works. Currently the ECALL handler is responsible for cleanup and jumping to the end-of-test loop, so if you don't change this mechanism the test will end upon reaching the first ECALL instruction.
e.g. override the gen_test_done method in combination with enabling this option.
@ctopal @GregAC
=> Add plusarg to enable ECALL in main randomized body

src/riscv_asm_program_gen.sv, src/riscv_instr_gen_config.sv, src/riscv_instr_pkg.sv, src/riscv_pmp_cfg.sv
The RISCV-DV PMP trap handler is quite an intricate procedure. In essence, it iterates through the PMP entries to find the one that caused the trap, then tries to amend that entry to give it the permissions it needs and continues the test program if that was successful. This works quite well when most entries are unlocked since whenever you get an access fault, the entry is changed to allow the operation and the instruction is retried. However, there are a few problems with this approach:
- The checking for locked entries did not take into account that MML mode.
- In cases where most entries are locked (e.g. MML mode), tests would be very short ending after just the first failed load, store or fetch.
Besides the trap handling, the population of entries had some shortcomings,  which lead …
=> [pmp] Fix ePMP related trap handling

src/riscv_instr_pkg.sv
The `push/pop_gpr` routines currently do not work with the (cfg.enable_nested_interrupt) code as the user stack pointer gets overwritten. Change the routines to push the USP to the kernel stack, then pop it back off when restoring program state.
Also see https://github.com/lowRISC/ibex/pull/1875
=> Push/pop GPR routine fixes

src/riscv_pmp_cfg.sv
PMP supports up to 35 bits of physical address space when XLEN==32. For cores where this higher address space doesn't exist there is limited value in testing PMP settings that use it. This introduces a way to bias PMP configs so that the majority stay within the 32-bit space.
=> [pmp] Add option to constrain addresses to stay in 32-bit space

src/riscv_privileged_common_seq.sv
When its lower privilege mode, mstatus.MIE is not required to be 1 for taking interrupt.
So, randomizing mstatus.MPIE to 0/1 when interrupt is enabled, for lower privilege modes.
@GregAC @ctopal @hcallahan-lowrisc
Issue: https://github.com/lowRISC/ibex/issues/1825
=> randomizing mstatus.MIE when priv mode is lower than machine

src/riscv_pmp_cfg.sv
A constraint prevents MML being disabled when region configurations with W == 1 and R == 0 exist (this combination is reserved when MML is disabled).  This has the effect of making configurations with MML disabled rare as many random configurations will have at least one region with W == 1 and R == 0.
Add a solve before constraint so MML is decided upon before the W and R are randomized to more evenly generate MML and non-MML configurations.
=> [pmp] Ensure MML PMP configurations don't dominate.

src/riscv_page_table_list.sv
Fix issue #926 and issue #846, NEXT_LEVEL_PAGE entry's fields a,d,u should be 0, also valid_link_pte violate the constraint sw_legal_c. 
It will make spkie fall into infinite loop.
Also see issue#752 in SPIKE.
=> [page table]Fix issue #926 issue #846, NEXT_LEVEL_PAGE entry's fields a,d,u should be 0

run.py, scripts/renode_log_to_trace_csv.py, scripts/renode_wrapper.py, scripts/spike_log_to_trace_csv.py, scripts/whisper_log_trace_csv.py, yaml/iss.yaml
This PR provides enhancements to the ISS used with PyFlow Instruction Generator:
- Fixed logs created with spike in a scenario with multiple spaces and enabled parsing CSR writes from them
- Log file names produced by run.py now follow the same convention
- Added missing PC values to VeeR-ISS (a.k.a. whisper) log to CSV converter
- Enabled Renode as an Instruction Set Simulator
=> PyFlow log trace to csv improvements and Renode ISS support

.github/scripts/parse_testlist.py, .github/workflows/run-tests.yml, scripts/lib.py, yaml/simulator.yaml
Add additional tests to CI workflow
=> Extend CI matrix

euvm/riscv/gen/riscv_asm_program_gen.d, euvm/riscv/gen/riscv_load_store_instr_lib.d, euvm/riscv/gen/riscv_page_table_entry.d, euvm/riscv/gen/riscv_privileged_common_seq.d
Currently it is impossible to compile the eUVM-based instruction generator for RV32 due to errors in the code. This PR fixes those errors.
=> Fix RV32 support

scripts/lib.py
Hello,
We are using riscv-dv with two patches to verify [CVA6](https://github.com/openhwgroup/cva6/). We hope it will help everyone if those patches are made common.
1. The simulation was still running after hitting Ctrl-C. With this PR it is correctly killed. It is a continuation of work from @yanicasa fixing the same issue for timeouts.
2. We are using riscv-dv as a library with a relative path `dv.scripts`. Python 3.9 cannot find it albeit Python 3.7 had no issues finding it. To fix this, we found [this link](https://stackoverflow.com/questions/1944569/how-do-i-write-good-correct-package-init-py-files) and added an empty `__init__.py` file.
=> Fix Ctrl-C processing & use as lib with recent python versions

.github/workflows/build-spike.yml, .github/workflows/run-tests.yml, run.py, scripts/instr_trace_compare.py, scripts/lib.py, scripts/renode_wrapper.py, yaml/iss.yaml
This PR introduces the following changes:
* Allows for specifying privilege modes for simulation #984 
* Fixes disabling the `c` extension #988 
* Makes renode_wrapper more configurable #991
=> Improvements and fixes for VeeR-EL2 testing
